//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db20311Entities : DbContext
    {
        public db20311Entities()
            : base("name=db20311Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<CitaTaller> CitaTaller { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Concesionario> Concesionario { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<DetalleDevolucion> DetalleDevolucion { get; set; }
        public virtual DbSet<DetalleFacturaVenta> DetalleFacturaVenta { get; set; }
        public virtual DbSet<DetallePedidoCliente> DetallePedidoCliente { get; set; }
        public virtual DbSet<DevolucionVenta> DevolucionVenta { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EmpleadoCargo> EmpleadoCargo { get; set; }
        public virtual DbSet<FacturaVenta> FacturaVenta { get; set; }
        public virtual DbSet<FotosEmpleados> FotosEmpleados { get; set; }
        public virtual DbSet<Garantia> Garantia { get; set; }
        public virtual DbSet<ImagenesVehiculo> ImagenesVehiculo { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<NotaCredito> NotaCredito { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<PedidoCliente> PedidoCliente { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<ReclamoGarantia> ReclamoGarantia { get; set; }
        public virtual DbSet<ServicioTaller> ServicioTaller { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unidad> Unidad { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Perfil> Usuario_Perfil { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
