//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoCliente()
        {
            this.DetallePedidoCliente = new HashSet<DetallePedidoCliente>();
        }
    
        public int Id { get; set; }
        public string DocumentoCliente { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoCliente> DetallePedidoCliente { get; set; }
    }
}
