//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioTaller
    {
        public int Id { get; set; }
        public int IdCita { get; set; }
        public string DescripcionServicio { get; set; }
        public int CodigoEmpleado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public int Costo { get; set; }

        [JsonIgnore]
        public virtual CitaTaller CitaTaller { get; set; }
        [JsonIgnore]
        public virtual EmpleadoCargo EmpleadoCargo { get; set; }
    }
}
